name: mariosteininger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49757
title: Florale Formgebung Mario Steininger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060c08'
    - '#bed1d8'
    - '#389fa4'
    - '#e89478'
    - '#923417'
  brandStrength: 0
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0
purpose: []
