analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.74806
title: florale formgebung Florale Konzepte
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.125
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#93b4a0'
    - '#3b393c'
    - '#e0e6e3'
    - '#8f8e8f'
  lightness: 1
purpose: []
favicon: null
name: Mario Steininger
typography_spectrum: 0.50129
