name: mariosteininger
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49757
title: Florale Formgebung Mario Steininger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c3c3c3'
    - '#353631'
    - '#060203'
    - '#767676'
  brandStrength: 1
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0
purpose: []
