title: Florale Formgebung Mario Steininger
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#060c08'
    - '#bed1d8'
    - '#389fa4'
    - '#e89478'
    - '#923417'
  lightness: 0.875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: mariosteininger
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49757
layout_spectrum: 0.3276596
