typography_spectrum: 0.50129
color:
  saturation: 0.125
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#93b4a0'
    - '#3b393c'
    - '#e0e6e3'
    - '#8f8e8f'
  lightness: 1
opengraph:
  image: null
  type: null
  appId: '306110129438116'
layout_spectrum: 0.74806
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3c249bfc-7e34-4a26-8755-ae424a86e646.jpg
name: Mario Steininger
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31067074-73e1-480f-90a9-93d7e6aaef5f.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: florale formgebung Florale Konzepte
purpose: []
