name: mariosteininger
favicon: null
layout_spectrum: 0.5327554047107697
typography_spectrum: 0.8910092583391815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5097598726861179
  lightness: 0.9168761414475739
  saturation: 0.10978593537583947
  rhythmicContrast: 0.11445021186955273
purpose: []
