name: mariosteininger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49757
title: Florale Formgebung Mario Steininger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#757575'
    - '#dfdfdf'
    - '#05040d'
    - '#2c2c2c'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
